### ISSUE TITLE
RuntimeListMenuItem invoke on title item returns row 254 instead of 255

### ISSUE THREAD

**Issue by Netsplits** [davetcc/tcMenuLib#112]
I think there a bug on RunTimeListMenuItem. The callback of the menu RENDERFN_INVOKE row is 254 instead of 255 when interacting with the title row.

EDIT: I've found a sample where mentions 254 is for Back Menu Item. How can I disable the BackMenu. I don't wish the user can exit the menu until selected a item. Thanks.

**Comment by davetcc** [comment]
Can you not use a scroll choice item for this, as they must have a value, in all cases, they are basically an enumeration that can be defined at runtime, either using the same custom function as a list, an array in RAM, or an array in EEPROM. See the documentation for scroll choice from the designer UI properties page.

**Comment by Netsplits** [comment]
Finally I used setRootMenu and created a menu on code. Works nice. Thanks.
