### ISSUE TITLE
Should getMenuItemById return submenu items?

### ISSUE THREAD

**Issue by Netsplits** [davetcc/tcMenuLib#113]
When using getMenuItemById looking for a submenu, the returned value is NULL.

Should the function return a pointer to the MenuItem or is the intended behaviour to return NULL on submenus?

**Comment by davetcc** [comment]
This is a bug, added to 2.2 as it's critical. I'll also add unit tests to ensure it always works going forward.

**Comment by davetcc** [comment]
Fix will be in 2.2, but is so simple you could patch it in, see above
