### ISSUE TITLE
Create silent version of setters so menu callback doesn't fire

### ISSUE THREAD

**Issue by dsap4004** [davetcc/tcMenuLib#14]
Create silent version of setters so menu callback doesn't fire. 
For example: If you want to update a boolean menu item that normally controls an output pin that is also controlled by another process. Currently, using `myMenu.setBoolean(pinState);` will change the menu item and fire the callback. If the callback modifies the pinState 
`void CALLBACK_FUNCTION onMyMenu(int id) {
  pinState = !pinState;
  }`
then additional code is needed to keep track if you are just updating the menu item and keep the callback from changing the pinState again.

**Comment by davetcc** [comment]
will be released in 1.3.1
