### ISSUE TITLE
Is there a way to save single MenuItem's value to EEPROM ?

### ISSUE THREAD

**Issue by luwenjin** [davetcc/tcMenuLib#167]
I have a bunch of settings  under `Settings` Menu, and I also have some standalone options under other menus.

These stand alone options need to be saved when changed.
But currently, it seems I can only save the whole menu data to EEPROM, which may feel a bit odd to the users.

It would be nice if we can save single MenuItem's value to EEPROM.

**Comment by davetcc** [comment]
For questions like this should we start using the github discussions? Something that turns out to be an issue can easily be converted into an issue from there.

**Comment by luwenjin** [comment]
Sorry, I was worrying that if I put all (UI&lib) issues in the UI's repo, it would make your git less organized.
Since you like it that way, I'm also glad to post issues there for convenience 😄 

I'll move this issue there.

**Comment by davetcc** [comment]
I'll reopen it to track the work.

**Comment by davetcc** [comment]
See https://github.com/davetcc/tcMenu/issues/250 for the main issue

**Comment by davetcc** [comment]
https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/menu-eeprom-integrations/#loading-or-saving-a-single-menu-item
