### ISSUE TITLE
Minor UI issues in TCMenu Designer

### ISSUE THREAD

**Issue by mmilesg** [davetcc/tcMenuLib#183]
Hi Dave,
   I just wanted to point out a few minor issues in the designer. None of this effects functionality, but addressing these issues would make the UI a bit more polished.
These issues are all present in 3.0.0

1.
The preview for default value seems to lag one keystroke behind input in any field (here showing RP instead of RPM). This is particularly confusing when the updates don't immediately reflect changes in Offset or Divisor
![image](https://user-images.githubusercontent.com/94007807/216666806-1428889f-1ffc-44ea-80a3-9fd87ed60de8.png)

2.
Scroll bars can be cut off entirely if the UI window is too small. Probably best if the minimum window size is increased, or scroll bars are made to always stick to the right edge of the screen. Shown here partially obscured, but it can be completely hidden.
![image](https://user-images.githubusercontent.com/94007807/216667913-d803c94f-ae5c-4b8d-98fe-260b7370c8f4.png)
Also shown: some text labels are truncated with "..." when there is still enough room to view the whole field

3. 
Long menu variable names are obscured by the "X". This effects at least the last 2 characters of names that exceed the width of the text box. Both cursor and characters are obscured
![image](https://user-images.githubusercontent.com/94007807/216668630-69d26af1-775b-4fbc-847b-90eef877d660.png)

Obviously nothing critical here, I just thought it might be helpful to bring these to your attention. Thanks!

**Comment by davetcc** [comment]
I've fixed first one, scroll bar wise I've made the layouts work a bit better, but window sizing, I'll see if I can prevent it getting too small but this is very minor.

For the cross in text fields- https://github.com/davetcc/tcMenu/issues/306
