### ISSUE TITLE
TcMenu 3.1.0 not released in PlatformIO registry

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenuLib#184]
After TcMenu Designer 3.1.0 was released, I'm not able to compile my project. It requires TcMenu library 3.1.0 but it wasn't released in PlatformIO registry.

Same with IoAbstraction library.

![image](https://user-images.githubusercontent.com/4460766/218670003-61054acf-b5c3-4c15-8e25-38d2cd748919.png)

**Comment by davetcc** [comment]
Apologies released it just now. Along with IoAbstraction 3.1.0

**Comment by davetcc** [comment]
Please let me know if that fixed the issue.

I think for future releases I need to have a runbook in excel or similar, so that I can keep track of all the steps, of which there are many.

**Comment by davetcc** [comment]
Update is that I have spun up an AWS Ubuntu image and started to install the build server dependencies, so soon I will have a production build of 3.1 ready

**Comment by davetcc** [comment]
I’ll keep open until the Linux package is built.

**Comment by davetcc** [comment]
Closing out now, if there are any residual actions left to be done, please reopen.
