### ISSUE TITLE
Create a multi part editor, and apply to the text menu item

### ISSUE THREAD

**Issue by davetcc** [davetcc/tcMenuLib#19]
In order to configure wifi or other more complex settings on the device, a simple system for editing complex text items needs to be implemented.

This is the first part of a two-part change, where the second part will bring in support for Time, Date and IpAddresses.

The first part is to handle multi-part editing in the renderer such that a text item can be changed a field at a time and becomes based on a new abstract class MultiPartMenuItem.

**Comment by dsap4004** [comment]
I could see a version of this for numerical or time input as well. At the moment the only way to input multiple numbers is multiple menu items.

**Comment by davetcc** [comment]
Agreed, we could probably add new menu items that supported times (and possibly eventually dates).

My plan is to make adding new menu item types much easier too. At the moment there's quite a bit of work to do in both the remote API and in the rendering and editing.

Dates are more tricky as there are many rules, however, times have far fewer rules and could be targeted first.

**Comment by davetcc** [comment]
Linked with #23
