### ISSUE TITLE
Take over display causes garbled text when using u8g2 library and attached code

### ISSUE THREAD

**Issue by emaayan** [davetcc/tcMenuLib#191]
**Describe the bug**
when using renderer.takeOverDisplay(myDisplayCallback);   on a callback function the screen is garbled 

**Confirm that the bug is in the embedded library**
If the bug is in the designer, or you are not sure, raise in the main [tcMenu repo](https://github.com/davetcc/tcMenu).

**Commerical or personal/community use**
personal 

**To Reproduce**
use the follwoing code with esp32 and ss1306 oled screen 
`
```
#include "menuShow_menu.h"

#define CS 5
#define DC 17   // 16
#define RESET 4 // 17
u8g2_uint_t writeUTF8(const uint8_t *font, const u8g2_uint_t line, const u8g2_uint_t x, const char *buff, bool rtl = false)
{
    _oled.setFont(font);
    return _oled.drawExtUTF8(x, line, rtl ? 1 : 0, NULL, buff);
}
void myDisplayCallback(unsigned int encoderValue, RenderPressMode clicked)
{
    if (clicked == RPRESS_HELD)
    {
        renderer.giveBackDisplay();
    }
    else
    {        
        _oled.clearBuffer();                  
        _oled.setFont(u8g2_font_ncenB08_tr);  
        _oled.drawStr(0, 10, "Hello World!"); 
        _oled.sendBuffer();      
    }
}

void setup()
{
    setupMenu();
    renderer.takeOverDisplay(myDisplayCallback);    
}

void loop()
{
    taskManager.runLoop();
}

void CALLBACK_FUNCTION onExit(int id)
{
    renderer.takeOverDisplay(myDisplayCallback);
}
```
`

**Expected behavior**
when exiting the menu the string hello world should remain 

**Screenshots**
![image](https://user-images.githubusercontent.com/13434544/232080224-e88127e6-c3ef-46c0-bddd-131be5ac3f19.png)

**Device Specs**
esp32 
1.3" OLED Module 1.3 inch LCD Screen Display Module Blue 128X64 I2C Communicate 128*64 4P

**Comment by davetcc** [comment]
The code doesn't look quite right, you need to change the text color (and drawing mode), it is sometimes set to XOR in tcMenu. At the very least I think you'd need to add `_oled.setDrawColor(WHITE);`.

**Comment by emaayan** [comment]
setting color to white worked, but that never appeared in the samples , this only happens in the menu switching , also this forces the code to be tied to a specific color oled, even though it only has one color.

**Comment by davetcc** [comment]
The samples for this use the device drawable means of drawing instead of native library calls.

The take over display needs you to reset the display library to a known state just as you would if you drew yourself on the display.

**Comment by davetcc** [comment]
Closing as not an issue.

**Comment by emaayan** [comment]
> 

i believe this is something that also needs to be in the docs for the takeoverDispaly

**Comment by davetcc** [comment]
If you think something is missing in an example why not raise a PR with additional documentation in place?
