### ISSUE TITLE
After calling notifyStructureChanged any item being edited cannot reach full range

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenuLib#209]
**Describe the bug**
I observed (and also others reported to me) that with the latest version of TcMenu, users can't set the menu to some values using the up/down buttons.

An example: User wants to change a default time "07:00" into "19:00". He confirms the item, an edit mode is set. User presses the up button but the maximum number he can set is 10:00, despite the allowed range is 24-hour.

I observed this behavior elsewhere as well. I believe there is a regression within the library. I will try to get more information.

**Confirm that the bug is in the embedded library**
It is in the library.

**To Reproduce**
Create a text menu item representing time. Try to modify the value via menu.

https://github.com/davetcc/tcMenuLib/assets/4460766/9854c7de-f9f9-4153-87ab-fbfc08d27933

**Expected behavior**
All values from the allowed range should be allowed to be set.

**Comment by davetcc** [comment]
Can you let me know the hardware setup and steps to get it into a bad state so I can try and recreate it?

**Comment by davetcc** [comment]
Also, is it restricted to time menu items, or more general?

**Comment by vzahradnik** [comment]
I found the culprit. There was an issue in my code. In the top level menu I have a read-only text item to display date and time. This item is updated once per second. If `menuMgr.notifyStructureChanged()` is called, this issue is reproducible.

I don't know whether there's a race condition and why the menu is still editable to some degree. But now I don't see this as a bug in TcMenu. Maybe an enhancement. Hence I'm closing the issue.

```cpp
    // Update date and time
    menuCurrentTime.setVisible(true);
    strncpy(minfoCurrentTime.name, dateTimeManager.getDateTimeString(), sizeof(minfoCurrentTime.name));
    taskManager.scheduleFixedRate(1, [] {
        strncpy(minfoCurrentTime.name, dateTimeManager.getDateTimeString(), sizeof(minfoCurrentTime.name));
        // menuMgr.notifyStructureChanged();
    }, TIME_SECONDS);
```

**Comment by davetcc** [comment]
I mean the notifyStructureChanged method essentially completely rebuilds the menu from scratch, assuming the menu tree has been altered, it was never intended to be used in that way.

I think the best thing here is to discuss what that was trying to achieve and see if there's a better way to do it, or even put in a new feature if need be to support it. Not only is this likely to cause race conditions, but it is also doing a very time-consuming operation that's only supposed to happen when the menu on display changes.

**Comment by vzahradnik** [comment]
Here is the use case:

In the root menu I have 3 items:
- Current date and time
- Network state : online/offline
- Settings submenu

To update these first two items, I created a task manager task with an update interval 1 second. This is the interval when this function was called.

The menu structure was indeed changed. But it was on a screen which may not always be visible. And that was the only change I did: I call this function only when the screen (root menu) is currently active.

Still, it's interesting that editing items in one direction (decreasing a value) worked OK.

**Comment by vzahradnik** [comment]
Maybe I have one tip for improvement. Often I'm modifying just one part of the screen (some nested submenu).

If the operation is so costly, why not just update the items nested in a submenu? This could be specified as an optional parameter (submenu ID).

**Comment by davetcc** [comment]
Are you changing the structure of the menu every second? IE inserting a new menu item or removing existing menu items from the graph? That's the only time you need to notify structure changes. Regular changes in value are handled automatically as long as the setter method is used on the menu item. And even if it is not, you would just call setChanged(..) on the item.

**Comment by davetcc** [comment]
>        strncpy(minfoCurrentTime.name, dateTimeManager.getDateTimeString(), sizeof(minfoCurrentTime.name));

I can't infer exactly what you're trying to do here, but it seems like you want an item with no name/title. Rather than the above, why not create a grid position and tell that item only to render the value?

```
    factory.addGridPosition(&menuMyItem, GridPosition(GridPosition::DRAW_TEXTUAL_ITEM, GridPosition::JUSTIFY_LEFT_VALUE_ONLY, row));
```

**Comment by vzahradnik** [comment]
Most of the time I'm changing the content of text items, etc. Also I use to change the item visibility based on some conditions.

I will try the `setChanged(...)`, I agree that it will slightly improve the efficiency of my code.

> you want an item with no name/title

Correct.

> why not create a grid position and tell that item only to render the value?

I like having all my menu items together in the project file. Also, I don't want to display these hidden items all the time. Sometimes they are just shown if some conditions are met. For example:

Temperature and humidity:
Temp 1: xx C
Temp 2: xx C

vs.

Temp 1: DISCONNECTED
Temp 2: DISCONNECTED

Just by turning item visibility on and off I can achieve the result I want. Sometimes just one temp sensor is faulty and the other one shows the value. If this item wasn't defined as a menu item, I would mess with the grid on all such changes.

**Comment by davetcc** [comment]
I'll reopen this for the side effect of calling the notify method. I am going to make a change to ensure edit mode is completely ended on structure change.

**Comment by davetcc** [comment]
So on structure notify the renderer should:

1. Completely clear the editing status.
2. Completely clear the screen.
3. Completely recalculate the drawing order.

**Comment by davetcc** [comment]
This has been tested and is now known working.
