### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by AlexFundorin** [davetcc/tcMenuLib#35]
Can we have a simple, universal example of a working sketch for U8G2 lib (OLED), without Ethernet, color GFX display and EEPROM?

**Comment by davetcc** [comment]
I'll create a simple example of using U8G2 on a 32-bit board. Probably an ESP32 but the idea would be generally applicable to any board. This would also be useful for anyone using Adafruit_GFX based drivers as they work the same way.
