### ISSUE TITLE
Add new callback OnItemCommitted(int id) 

### ISSUE THREAD

**Issue by 0sander** [davetcc/tcMenuLib#56]
Add a new callback function that is called once a menuitem has been committed. This function should not be called every time a change is made but only once when the change is committed by the user.

**Comment by davetcc** [comment]
See https://github.com/davetcc/tcMenuLib/tree/master/examples/unoSsd1306Ascii where I've added a commit handler. I've also added one to the dfRobot project too. Will be released very soon.
