### ISSUE TITLE
A user defined unique Identifier (ID) won't be used by designer - it just disappears

### ISSUE THREAD

**Issue by fs63** [davetcc/tcMenuLib#97]
Hi Dave,
In the designer I've tried assigning my own ID to a new menuItem, yet it gets lost and won't appear in the designer and not in the generated code. Out of curiosity I've tried with an already used ID - this "error" is handled by the designer correctly. I also checked with a couple of different itemTypes, all the same. 
As the process of coding sometimes isn't straight forward for me, the feature of 'user defined Item-IDs' would great to have. And I believe this might have been the initial intention ...

Thanks a lot, Frank

**Comment by davetcc** [comment]
Hi there, thanks for reporting this, I'll check this in all three versions, Mac, Windows and Linux. On the mac I just checked and it's not even editable. We'll make it work consistently across all three.

**Comment by fs63** [comment]
Pls see the other issue (forward declations) >> TcMenu Designer 1.7.13 from MS.
Tx a lot, Frank

**Comment by davetcc** [comment]
Started sorting this out now. and should be in the next beta version. Just got the Win10 version left to look at now. Was a simple fix for the Mac version, and already worked on the older Java version for Linux & Win 7/8

**Comment by davetcc** [comment]
This is already in the 2.0 BETA. It will be released to the store once it's gone through a test cycle.

All UIs act the same way now.
